# Generated by Django 4.2.10 on 2026-06-19 06:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='无人机名称')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('busy', '作业中'), ('maintenance', '维护中'), ('offline', '离线')], default='idle', max_length=20, verbose_name='状态')),
                ('battery', models.IntegerField(default=100, verbose_name='电量(%)')),
                ('max_flight_time', models.IntegerField(default=30, verbose_name='最大续航(分钟)')),
                ('payload', models.CharField(blank=True, max_length=200, verbose_name='载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '无人机',
                'verbose_name_plural': '无人机',
                'db_table': 'inspection_drone',
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='航线名称')),
                ('waypoints', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='航点轨迹')),
                ('waypoints_data', models.JSONField(blank=True, default=list, verbose_name='航点详情')),
                ('altitude', models.FloatField(default=50, verbose_name='飞行高度(m)')),
                ('speed', models.FloatField(default=8, verbose_name='飞行速度(m/s)')),
                ('estimated_duration', models.IntegerField(default=0, verbose_name='预计时长(分钟)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审批'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to='lines.line', verbose_name='所属线路')),
            ],
            options={
                'verbose_name': '飞行航线',
                'verbose_name_plural': '飞行航线',
                'db_table': 'inspection_flightroute',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='任务编号')),
                ('name', models.CharField(max_length=120, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('media_count', models.IntegerField(default=0, verbose_name='影像数量')),
                ('defect_count', models.IntegerField(default=0, verbose_name='缺陷数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='inspection.drone', verbose_name='无人机')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_tasks', to=settings.AUTH_USER_MODEL, verbose_name='飞手')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='inspection.flightroute', verbose_name='航线')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务',
                'db_table': 'inspection_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='inspection/%Y/%m/%d/', verbose_name='文件')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video', '视频')], default='image', max_length=10, verbose_name='类型')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='inspection/thumbs/%Y/%m/%d/', verbose_name='缩略图')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='拍摄位置')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='飞行高度(m)')),
                ('has_defect', models.BooleanField(default=False, verbose_name='是否有缺陷')),
                ('defect_count', models.IntegerField(default=0, verbose_name='缺陷数量')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inspection.inspectiontask', verbose_name='巡检任务')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='lines.tower', verbose_name='杆塔')),
            ],
            options={
                'verbose_name': '巡检影像',
                'verbose_name_plural': '巡检影像',
                'db_table': 'inspection_media',
                'ordering': ['-captured_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('insulator', '绝缘子'), ('tower', '塔体'), ('hardware', '金具'), ('conductor', '导线'), ('other', '其他')], default='insulator', max_length=20, verbose_name='缺陷类型')),
                ('subtype', models.CharField(max_length=40, verbose_name='缺陷子类')),
                ('severity', models.CharField(choices=[('critical', '危急'), ('major', '重大'), ('minor', '一般')], default='minor', max_length=10, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('confirmed', '已确认'), ('rejected', '已驳回')], default='pending', max_length=12, verbose_name='状态')),
                ('bbox', models.JSONField(blank=True, default=dict, verbose_name='缺陷框')),
                ('confidence', models.FloatField(default=0.0, verbose_name='AI置信度')),
                ('description', models.TextField(blank=True, verbose_name='缺陷描述')),
                ('review_note', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspection.inspectionmedia', verbose_name='影像')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspection.inspectiontask', verbose_name='巡检任务')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='lines.tower', verbose_name='杆塔')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
                'db_table': 'inspection_defect',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('defect', '缺陷告警'), ('device', '设备告警'), ('weather', '气象告警'), ('other', '其他')], default='defect', max_length=20, verbose_name='告警类型')),
                ('level', models.CharField(choices=[('critical', '危急'), ('major', '重大'), ('minor', '一般')], default='minor', max_length=10, verbose_name='告警级别')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('content', models.TextField(blank=True, verbose_name='告警内容')),
                ('status', models.CharField(choices=[('open', '待处置'), ('processing', '处理中'), ('handled', '已处置'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('handle_note', models.TextField(blank=True, verbose_name='处置说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inspection.defect', verbose_name='关联缺陷')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL, verbose_name='处置人')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='lines.tower', verbose_name='杆塔')),
            ],
            options={
                'verbose_name': '隐患告警',
                'verbose_name_plural': '隐患告警',
                'db_table': 'inspection_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
