# Generated by Django 4.2.10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0001_initial'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='distance',
            field=models.FloatField(default=0, verbose_name='航线长度(米)'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_routes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='审核人',
            ),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', '草稿'),
                    ('pending_review', '待审核'),
                    ('approved', '已审批'),
                    ('rejected', '已驳回'),
                    ('archived', '已归档'),
                ],
                default='draft',
                max_length=20,
                verbose_name='状态',
            ),
        ),
        migrations.CreateModel(
            name='FlightRouteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('name', models.CharField(max_length=120, verbose_name='航线名称')),
                ('waypoints', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='航点轨迹')),
                ('waypoints_data', models.JSONField(blank=True, default=list, verbose_name='航点详情')),
                ('altitude', models.FloatField(default=50, verbose_name='飞行高度(m)')),
                ('speed', models.FloatField(default=8, verbose_name='飞行速度(m/s)')),
                ('distance', models.FloatField(default=0, verbose_name='航线长度(米)')),
                ('estimated_duration', models.IntegerField(default=0, verbose_name='预计时长(分钟)')),
                ('status', models.CharField(
                    choices=[
                        ('draft', '草稿'),
                        ('pending_review', '待审核'),
                        ('approved', '已审批'),
                        ('rejected', '已驳回'),
                        ('archived', '已归档'),
                    ],
                    default='draft',
                    max_length=20,
                    verbose_name='状态',
                )),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='创建人',
                )),
                ('line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='route_versions',
                    to='lines.line',
                    verbose_name='所属线路',
                )),
                ('route', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='versions',
                    to='inspection.flightroute',
                    verbose_name='航线',
                )),
            ],
            options={
                'verbose_name': '航线版本',
                'verbose_name_plural': '航线版本',
                'db_table': 'inspection_flightrouteversion',
                'ordering': ['route', '-version'],
                'unique_together': {('route', 'version')},
            },
        ),
    ]
