from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '__first__'),
        ('accounts', '__first__'),
        ('inspection', '0002_route_version_and_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='firmware_version',
            field=models.CharField(blank=True, default='v1.0.0', max_length=50, verbose_name='固件版本'),
        ),
        migrations.AddField(
            model_name='drone',
            name='signal_strength',
            field=models.IntegerField(default=100, verbose_name='信号强度(%)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='altitude',
            field=models.FloatField(default=0, verbose_name='高度(m)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='speed',
            field=models.FloatField(default=0, verbose_name='速度(m/s)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='heading',
            field=models.FloatField(default=0, verbose_name='航向(度)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='drone',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='drone',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间'),
        ),
        migrations.AddField(
            model_name='drone',
            name='last_report_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后上报时间'),
        ),
        migrations.AddField(
            model_name='drone',
            name='last_report_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('heartbeat', '心跳上报'),
                    ('telemetry', '遥测上报'),
                    ('media', '媒体上报'),
                    ('event', '事件上报'),
                    ('task_summary', '任务汇总上报'),
                ],
                max_length=20,
                verbose_name='最后上报类型',
            ),
        ),
        migrations.AddField(
            model_name='drone',
            name='current_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前任务ID'),
        ),
        migrations.AddField(
            model_name='drone',
            name='current_route_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前航线ID'),
        ),
        migrations.AddField(
            model_name='drone',
            name='current_line_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前线路ID'),
        ),
        migrations.AddField(
            model_name='drone',
            name='mqtt_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='MQTT认证Token'),
        ),
        migrations.CreateModel(
            name='DroneTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(verbose_name='上报时间')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('altitude', models.FloatField(default=0, verbose_name='高度(m)')),
                ('speed', models.FloatField(default=0, verbose_name='速度(m/s)')),
                ('heading', models.FloatField(default=0, verbose_name='航向(度)')),
                ('battery', models.IntegerField(default=100, verbose_name='电量(%)')),
                ('signal_strength', models.IntegerField(default=100, verbose_name='信号强度(%)')),
                ('satellites', models.IntegerField(default=0, verbose_name='卫星数')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(℃)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='风速(m/s)')),
                ('extra_data', JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='inspection.drone', verbose_name='无人机')),
            ],
            options={
                'verbose_name': '无人机遥测数据',
                'verbose_name_plural': '无人机遥测数据',
                'db_table': 'inspection_drone_telemetry',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='DroneEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(verbose_name='上报时间')),
                ('event_level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '异常'), ('critical', '严重')], default='info', max_length=20, verbose_name='事件级别')),
                ('event_category', models.CharField(choices=[('battery', '电量异常'), ('signal', '信号异常'), ('weather', '气象异常'), ('flight', '飞行异常'), ('device', '设备故障'), ('obstacle', '避障告警'), ('other', '其他')], default='other', max_length=30, verbose_name='事件类别')),
                ('event_code', models.CharField(blank=True, max_length=50, verbose_name='事件代码')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='高度(m)')),
                ('handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('extra_data', JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inspection.drone', verbose_name='无人机')),
            ],
            options={
                'verbose_name': '无人机事件',
                'verbose_name_plural': '无人机事件',
                'db_table': 'inspection_drone_event',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='DroneMediaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(verbose_name='上报时间')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('panorama', '全景图')], default='image', max_length=20, verbose_name='媒体类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件访问链接')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='缩略图链接')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='高度(m)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='航向(度)')),
                ('tower_id', models.IntegerField(blank=True, null=True, verbose_name='关联杆塔ID')),
                ('uploaded', models.BooleanField(default=False, verbose_name='是否已入库')),
                ('media_id', models.IntegerField(blank=True, null=True, verbose_name='对应影像ID')),
                ('extra_data', JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reports', to='inspection.drone', verbose_name='无人机')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_reports', to='inspection.inspectiontask', verbose_name='巡检任务')),
            ],
            options={
                'verbose_name': '无人机媒体上报',
                'verbose_name_plural': '无人机媒体上报',
                'db_table': 'inspection_drone_media_report',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='DroneTaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(verbose_name='上报时间')),
                ('task_status', models.CharField(choices=[('takeoff', '起飞'), ('climbing', '爬升中'), ('cruising', '巡航中'), ('turning', '转弯中'), ('descending', '下降中'), ('landing', '降落中'), ('paused', '暂停'), ('returning', '返航中'), ('completed', '任务完成'), ('aborted', '任务中止'), ('error', '异常中断')], max_length=20, verbose_name='任务状态')),
                ('flight_phase', models.CharField(blank=True, max_length=50, verbose_name='飞行阶段')),
                ('current_waypoint_index', models.IntegerField(default=0, verbose_name='当前航点索引')),
                ('total_waypoints', models.IntegerField(default=0, verbose_name='总航点数')),
                ('progress', models.FloatField(default=0, verbose_name='任务进度(%)')),
                ('flight_distance', models.FloatField(default=0, verbose_name='已飞行距离(m)')),
                ('remaining_distance', models.FloatField(default=0, verbose_name='剩余距离(m)')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='已用时间(秒)')),
                ('remaining_time', models.IntegerField(default=0, verbose_name='预计剩余时间(秒)')),
                ('photos_taken', models.IntegerField(default=0, verbose_name='已拍摄照片数')),
                ('videos_recorded', models.IntegerField(default=0, verbose_name='已录制视频数')),
                ('battery_used', models.IntegerField(default=0, verbose_name='已消耗电量(%)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('altitude', models.FloatField(default=0, verbose_name='高度(m)')),
                ('speed', models.FloatField(default=0, verbose_name='速度(m/s)')),
                ('heading', models.FloatField(default=0, verbose_name='航向(度)')),
                ('extra_data', JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_summaries', to='inspection.drone', verbose_name='无人机')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_summaries', to='inspection.flightroute', verbose_name='飞行航线')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_summaries', to='inspection.inspectiontask', verbose_name='巡检任务')),
            ],
            options={
                'verbose_name': '无人机任务汇总',
                'verbose_name_plural': '无人机任务汇总',
                'db_table': 'inspection_drone_task_summary',
                'ordering': ['-report_time'],
            },
        ),
    ]
