# Generated by Django 4.2.10 on 2026-06-19 06:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='线路名称')),
                ('voltage', models.CharField(choices=[('110kV', '110kV'), ('220kV', '220kV'), ('500kV', '500kV'), ('750kV', '750kV'), ('1000kV', '1000kV')], default='220kV', max_length=20, verbose_name='电压等级')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='线路几何')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '输电线路',
                'verbose_name_plural': '输电线路',
                'db_table': 'lines_line',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='区段名称')),
                ('start_km', models.FloatField(default=0, verbose_name='起始公里标')),
                ('end_km', models.FloatField(default=0, verbose_name='结束公里标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lines.line', verbose_name='所属线路')),
            ],
            options={
                'verbose_name': '线路区段',
                'verbose_name_plural': '线路区段',
                'db_table': 'lines_section',
                'ordering': ['line', 'start_km'],
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, verbose_name='杆塔编号')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='杆塔位置')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='杆塔高度(m)')),
                ('tower_type', models.CharField(choices=[('straight', '直线塔'), ('angle', '转角塔'), ('terminal', '终端塔'), ('tension', '耐张塔')], default='straight', max_length=20, verbose_name='杆塔类型')),
                ('sequence', models.IntegerField(default=0, verbose_name='序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='lines.line', verbose_name='所属线路')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towers', to='lines.section', verbose_name='所属区段')),
            ],
            options={
                'verbose_name': '杆塔',
                'verbose_name_plural': '杆塔',
                'db_table': 'lines_tower',
                'ordering': ['line', 'sequence'],
            },
        ),
    ]
