# Generated by Django 4.2.10 on 2026-06-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDefectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_defects', models.IntegerField(default=0, verbose_name='缺陷总数')),
                ('critical_count', models.IntegerField(default=0, verbose_name='危急缺陷')),
                ('major_count', models.IntegerField(default=0, verbose_name='重大缺陷')),
                ('minor_count', models.IntegerField(default=0, verbose_name='一般缺陷')),
                ('trend_data', models.JSONField(blank=True, default=dict, verbose_name='趋势数据')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_stats', to='lines.line', verbose_name='线路')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defect_stats', to='lines.section', verbose_name='区段')),
            ],
            options={
                'verbose_name': '区段缺陷统计',
                'verbose_name_plural': '区段缺陷统计',
                'db_table': 'stats_section_defect',
                'ordering': ['-total_defects'],
            },
        ),
        migrations.CreateModel(
            name='LineDefectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_defects', models.IntegerField(default=0, verbose_name='缺陷总数')),
                ('critical_count', models.IntegerField(default=0, verbose_name='危急缺陷')),
                ('major_count', models.IntegerField(default=0, verbose_name='重大缺陷')),
                ('minor_count', models.IntegerField(default=0, verbose_name='一般缺陷')),
                ('tower_count', models.IntegerField(default=0, verbose_name='杆塔数')),
                ('defect_rate', models.FloatField(default=0, verbose_name='缺陷率')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defect_stats', to='lines.line', verbose_name='线路')),
            ],
            options={
                'verbose_name': '线路缺陷统计',
                'verbose_name_plural': '线路缺陷统计',
                'db_table': 'stats_line_defect',
                'ordering': ['-total_defects'],
            },
        ),
    ]
