# Generated by Django 4.2.10 on 2026-06-19 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('description', models.TextField(verbose_name='工单描述')),
                ('severity', models.CharField(choices=[('critical', '危急'), ('major', '重大'), ('minor', '一般')], default='minor', max_length=10, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '普通'), ('low', '低')], default='normal', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('created', '已创建'), ('assigned', '已派发'), ('processing', '处理中'), ('review', '待复核'), ('closed', '已闭环'), ('cancelled', '已取消')], default='created', max_length=20, verbose_name='状态')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='计划开始')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='计划完成')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际完成')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='闭环时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='inspection.defect', verbose_name='关联缺陷')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='lines.tower', verbose_name='杆塔')),
            ],
            options={
                'verbose_name': '消缺工单',
                'verbose_name_plural': '消缺工单',
                'db_table': 'ops_workorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('assign', '派发'), ('start', '开始处理'), ('progress', '进度更新'), ('submit_review', '提交复核'), ('review_pass', '复核通过'), ('review_fail', '复核驳回'), ('close', '闭环'), ('cancel', '取消'), ('note', '备注')], max_length=20, verbose_name='动作')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='目标状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ops.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单日志',
                'verbose_name_plural': '工单日志',
                'db_table': 'ops_workorder_log',
                'ordering': ['created_at'],
            },
        ),
    ]
